version: '3.8'

services:
  mariadb:
    image: mariadb:latest
    container_name: httpseeker_mariadb
    restart: always
    ports:
      - "6306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: "123456"
      MYSQL_DATABASE: test
      MYSQL_ROOT_HOST: "%"
    volumes:
      - mariadb_data:/var/lib/mysql
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    healthcheck:
      test: ["CMD", "healthcheck.sh", "--connect", "--innodb_initialized"]
      interval: 10s
      timeout: 5s
      retries: 3

  redis:
    image: redis:latest
    container_name: httpseeker_redis
    restart: always
    ports:
      - "6379:6379"
    command: redis-server --requirepass 123456 --appendonly yes
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "--raw", "incr", "ping"]
      interval: 10s
      timeout: 5s
      retries: 3

volumes:
  mariadb_data:
    driver: local
  redis_data:
    driver: local